export const SUPABASE_URL: any = process.env.NEXT_PUBLIC_SUPABASE_URL;
export const SUPABASE_ANON_KEY: any = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;
export const JWT_SECRET = process.env.NEXT_PUBLIC_JWT_SECRET;
export const CLIENT_ID = process.env.NEXT_PUBLIC_CLIENT_ID;
export const CLIENT_SECRET = process.env.NEXT_PUBLIC_CLIENT_SECRET;
export const SPOTIFY_CLIENT_ID = process.env.NEXT_PUBLIC_SPOTIFY_CLIENT_ID;
export const SPOTIFY_CLIENT_SECRET =
  process.env.NEXT_PUBLIC_SPOTIFY_CLIENT_SECRET;
export const SPOTIFY_REFRESH_TOKEN =
  process.env.NEXT_PUBLIC_SPOTIFY_REFRESH_TOKEN;
